FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MyDatabaseApp/MyDatabaseApp.csproj", "MyDatabaseApp/"]
RUN dotnet restore "MyDatabaseApp/MyDatabaseApp.csproj"
COPY . .
WORKDIR "/src/MyDatabaseApp"
RUN dotnet build "MyDatabaseApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyDatabaseApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyDatabaseApp.dll"]
